### ISSUE TITLE
double-check v11 (protos for v20)

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/gator_bit#4]
1) Is "Revised by: " and the reviser's name present? [NO]
comment: missing in schematic page 2

2) Is the version number correct? [YES]
comment: yep, but let's not forget to jump it to v20 when we go to reds

3) Have you verified that the BOM in Sparkle is accurate (also checking for PROD_ID, NAME, VALUE, PREFIX)? [NO]
comment: you 100 ohm resistors are not correct in sparkle

4) If this design requires special ordering or production assembly instructions, have the symbols/packages been added with notes? (PCB thickness, humidity sensitivity, etc.) [YES]
comment: yep, black gloss. nice.

**Comment by AndyEngland521** [comment]
Fixed and pushed and ordered, oh my!
